version: '3.1'

services:
  db:
    image: arm64v8/postgres:13
    environment:
      POSTGRES_DB: prhunter
      POSTGRES_USER: localdev
      POSTGRES_PASSWORD: localdev
    ports:
      - 5432:5432
