crypto:
  ethBountyFactoryAddress: ${BOUNTY_FACTORY_ETH_ADDRESS:invalid}
  ethEtherscanUrl: "https://ropsten.etherscan.io/"
  ethRpcUrl: ${ETH_RPC_URL:invalid}
  ethPkey: ${ETH_PKEY:invalid}
  ethGasLimit: 8000000
  bscBountyFactoryAddress: ${BOUNTY_FACTORY_BSC_ADDRESS:invalid}
  bscEtherscanUrl: "https://testnet.bscscan.com/"
  bscRpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545/"
  bscGasLimit: 30000000
  isTestNet: true