spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prhunter
    username: localdev
    password: localdev
  jpa:
    properties:
      hibernate:
        dialect = org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:invalid}
            client-secret: ${GITHUB_CLIENT_SECRET:invalid}

server:
  servlet:
    contextPath: /api

github:
  appId: ${GITHUB_APP_ID:invalid}
  clientId: ${GITHUB_CLIENT_ID:invalid}
  clientSecret: ${GITHUB_CLIENT_SECRET:invalid}
  webhookSecret: ${GITHUB_WEBHOOK_SECRET:invalid}
  privateKey: ${GITHUB_PRIVATE_KEY:invalid}

logging:
  level:
    org.springframework: debug
