crypto:
  ethBountyFactoryAddress: ${BOUNTY_FACTORY_ETH_ADDRESS:invalid}
  ethEtherscanUrl: "https://etherscan.io/"
  ethRpcUrl: ${ETH_RPC_URL:invalid}
  ethPkey: ${ETH_PKEY:invalid}
  ethGasLimit: 21000000
  bscBountyFactoryAddress: ${BOUNTY_FACTORY_BSC_ADDRESS:invalid}
  bscEtherscanUrl: "https://bscscan.com/"
  bscRpcUrl: "https://bsc-dataseed.binance.org/"
  bscGasLimit: 80000000
  isTestNet: false