spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prhunter
    username: localdev
    password: localdev
    hikari:
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types:
            print:
              banner: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:invalid}
            client-secret: ${GITHUB_CLIENT_SECRET:invalid}
            redirect-uri-template: ${GITHUB_REDIRECT_URL:invalid}
  main:
    banner-mode: off
            
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  servlet:
    contextPath: /


firebase:
  privateKey: ${FIREBASE_PRIVATE_KEY:""}

github:
  baseUrl: "https://api.github.com"
  appId: ${GITHUB_APP_ID:invalid}
  successUrl: ${GITHUB_SUCCESS_URL:http://localhost:3000/oauth2/redirect}
  clientId: ${GITHUB_CLIENT_ID:invalid}
  clientSecret: ${GITHUB_CLIENT_SECRET:invalid}
  webhookSecret: ${GITHUB_WEBHOOK_SECRET:invalid}
  privateKey: ${GITHUB_PRIVATE_KEY:invalid}
  redirectUrl: ${GITHUB_REDIRECT_URL:invalid}

twilio:
  apiKey: ${TWILIO_KEY:invalid}

auth:
  jwtSecret: ${JWT_SECRET:9c898633-a4f5-43fa-a81b-18de8cd969c7}


logging:
  level:
    io.ktor: info
    org.springframework: info
    org.springframework.security: info
    org.zalando.logbook: info
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
