spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prhunter
    username: localdev
    password: localdev
    hikari:
      maximumPoolSize: 5
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types:
            print:
              banner: false
  main:
    banner-mode: off
            
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  servlet:
    contextPath: /

prhunter:
  frontendUrl: ${FRONTEND_URL:http://localhost:3000}

firebase:
  privateKey: ${FIREBASE_PRIVATE_KEY:""}

github:
  baseUrl: "https://api.github.com"
  appId: ${GITHUB_APP_ID:invalid}
  webhookSecret: ${GITHUB_WEBHOOK_SECRET:invalid}
  privateKey: ${GITHUB_PRIVATE_KEY:invalid}

crypto:
  ethBountyFactoryAddress: ${BOUNTY_FACTORY_ETH_ADDRESS:invalid}
  ethEtherscanUrl: "https://ropsten.etherscan.io/"
  ethRpcUrl: ${ETH_RPC_URL:invalid}
  ethPkey: ${ETH_PKEY:invalid}
  ethGasLimit: 8000000
  bscBountyFactoryAddress: ${BOUNTY_FACTORY_BSC_ADDRESS:invalid}
  bscEtherscanUrl: "https://testnet.bscscan.com/"
  bscRpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545/"
  bscGasLimit: 9000000
  isTestNet: true

twilio:
  apiKey: ${TWILIO_KEY:invalid}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
