spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prhunter
    username: localdev
    password: localdev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types:
            print:
              banner: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:invalid}
            client-secret: ${GITHUB_CLIENT_SECRET:invalid}
            redirect-uri-template: "https://api.prhunter.io/login/oauth2/code/github"
            
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

server:
  servlet:
    contextPath: /

github:
  baseUrl: "api.github.com"
  appId: ${GITHUB_APP_ID:invalid}
  successUrl: ${GITHUB_SUCCESS_URL:https://prhunter.io/oauth2/redirect}
  clientId: ${GITHUB_CLIENT_ID:invalid}
  clientSecret: ${GITHUB_CLIENT_SECRET:invalid}
  webhookSecret: ${GITHUB_WEBHOOK_SECRET:invalid}
  privateKey: ${GITHUB_PRIVATE_KEY:invalid}

auth:
  jwtSecret: ${JWT_SECRET:9c898633-a4f5-43fa-a81b-18de8cd969c7}

logging:
  level:
    org.springframework: info
    org.springframework.security: info
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
